FROM arm32v7/node:10-slim

WORKDIR /app/

COPY package*.json ./
RUN  apt-get update -y
RUN  apt-get install -y python
RUN apt-get install -y build-essential

RUN npm install --production

COPY app.js ./

USER root

CMD ["node", "app.js"]
